version: '3.8'
name: organice-ops

services:

  jenkins:
    container_name: jenkins
    build:
      context: ../organice-ops/
      dockerfile_inline: |
        FROM jenkins/jenkins:jdk17
        USER root
        RUN apt-get update && apt-get install -y lsb-release
        RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
          https://download.docker.com/linux/debian/gpg
        RUN echo "deb [arch=$(dpkg --print-architecture) \
          signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
          https://download.docker.com/linux/debian \
          $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
        RUN apt-get update && apt-get install -y docker-ce-cli
        USER jenkins
        # RUN jenkins-plugin-cli --plugins "blueocean docker-workflow"
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - ./data/jenkins_home:/var/jenkins_home
    restart: always
    networks:
      - private-network

networks:
  private-network:
    driver: bridge